//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Managerr.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PruebasEntities : DbContext
    {
        public PruebasEntities()
            : base("name=PruebasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CantidadEntregasPorMes> CantidadEntregasPorMes { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<RelEmpleadoSalario> RelEmpleadoSalario { get; set; }
    
        public virtual ObjectResult<Nullable<decimal>> CantidadEntregasPorMes_C_datos(Nullable<int> idEmpleado, Nullable<int> mes, Nullable<int> idCantEntregas)
        {
            var idEmpleadoParameter = idEmpleado.HasValue ?
                new ObjectParameter("IdEmpleado", idEmpleado) :
                new ObjectParameter("IdEmpleado", typeof(int));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("Mes", mes) :
                new ObjectParameter("Mes", typeof(int));
    
            var idCantEntregasParameter = idCantEntregas.HasValue ?
                new ObjectParameter("IdCantEntregas", idCantEntregas) :
                new ObjectParameter("IdCantEntregas", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("CantidadEntregasPorMes_C_datos", idEmpleadoParameter, mesParameter, idCantEntregasParameter);
        }
    
        public virtual ObjectResult<CantidadEntregasPorMes_R_datos_Result> CantidadEntregasPorMes_R_datos(Nullable<int> idEmpleado, Nullable<int> iDMES)
        {
            var idEmpleadoParameter = idEmpleado.HasValue ?
                new ObjectParameter("IdEmpleado", idEmpleado) :
                new ObjectParameter("IdEmpleado", typeof(int));
    
            var iDMESParameter = iDMES.HasValue ?
                new ObjectParameter("IDMES", iDMES) :
                new ObjectParameter("IDMES", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CantidadEntregasPorMes_R_datos_Result>("CantidadEntregasPorMes_R_datos", idEmpleadoParameter, iDMESParameter);
        }
    
        public virtual ObjectResult<CtRol_R_datos_Result> CtRol_R_datos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CtRol_R_datos_Result>("CtRol_R_datos");
        }
    
        public virtual ObjectResult<Nullable<decimal>> Empleado_C_datos(string nombre, Nullable<int> idRol)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("IdRol", idRol) :
                new ObjectParameter("IdRol", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Empleado_C_datos", nombreParameter, idRolParameter);
        }
    
        public virtual ObjectResult<Empleado_R_datos_Result> Empleado_R_datos(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Empleado_R_datos_Result>("Empleado_R_datos", nombreParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Empleado_R_NuevoRegistro()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Empleado_R_NuevoRegistro");
        }
    }
}
