//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Managerr.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelEntregaBono
    {
        public int IdRelEntregaEmpleado { get; set; }
        public Nullable<int> IdEntrega { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
    }
}
