//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaC.ServicioEmpleado {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOEmpleado", Namespace="http://schemas.datacontract.org/2004/07/Managerr.DTO")]
    [System.SerializableAttribute()]
    public partial class DTOEmpleado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionRolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEntregasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdMesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double fBonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double fEntregasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double fISRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double fSalarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double fTotalBonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double fTotalEntregasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double fTotalGeneralField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double fTotalGeneralConISRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double fTotalSalarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionRol {
            get {
                return this.DescripcionRolField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionRolField, value) != true)) {
                    this.DescripcionRolField = value;
                    this.RaisePropertyChanged("DescripcionRol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEmpleado {
            get {
                return this.IdEmpleadoField;
            }
            set {
                if ((this.IdEmpleadoField.Equals(value) != true)) {
                    this.IdEmpleadoField = value;
                    this.RaisePropertyChanged("IdEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEntregas {
            get {
                return this.IdEntregasField;
            }
            set {
                if ((this.IdEntregasField.Equals(value) != true)) {
                    this.IdEntregasField = value;
                    this.RaisePropertyChanged("IdEntregas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMes {
            get {
                return this.IdMesField;
            }
            set {
                if ((this.IdMesField.Equals(value) != true)) {
                    this.IdMesField = value;
                    this.RaisePropertyChanged("IdMes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRol {
            get {
                return this.IdRolField;
            }
            set {
                if ((this.IdRolField.Equals(value) != true)) {
                    this.IdRolField = value;
                    this.RaisePropertyChanged("IdRol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double fBono {
            get {
                return this.fBonoField;
            }
            set {
                if ((this.fBonoField.Equals(value) != true)) {
                    this.fBonoField = value;
                    this.RaisePropertyChanged("fBono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double fEntregas {
            get {
                return this.fEntregasField;
            }
            set {
                if ((this.fEntregasField.Equals(value) != true)) {
                    this.fEntregasField = value;
                    this.RaisePropertyChanged("fEntregas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double fISR {
            get {
                return this.fISRField;
            }
            set {
                if ((this.fISRField.Equals(value) != true)) {
                    this.fISRField = value;
                    this.RaisePropertyChanged("fISR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double fSalario {
            get {
                return this.fSalarioField;
            }
            set {
                if ((this.fSalarioField.Equals(value) != true)) {
                    this.fSalarioField = value;
                    this.RaisePropertyChanged("fSalario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double fTotalBono {
            get {
                return this.fTotalBonoField;
            }
            set {
                if ((this.fTotalBonoField.Equals(value) != true)) {
                    this.fTotalBonoField = value;
                    this.RaisePropertyChanged("fTotalBono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double fTotalEntregas {
            get {
                return this.fTotalEntregasField;
            }
            set {
                if ((this.fTotalEntregasField.Equals(value) != true)) {
                    this.fTotalEntregasField = value;
                    this.RaisePropertyChanged("fTotalEntregas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double fTotalGeneral {
            get {
                return this.fTotalGeneralField;
            }
            set {
                if ((this.fTotalGeneralField.Equals(value) != true)) {
                    this.fTotalGeneralField = value;
                    this.RaisePropertyChanged("fTotalGeneral");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double fTotalGeneralConISR {
            get {
                return this.fTotalGeneralConISRField;
            }
            set {
                if ((this.fTotalGeneralConISRField.Equals(value) != true)) {
                    this.fTotalGeneralConISRField = value;
                    this.RaisePropertyChanged("fTotalGeneralConISR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double fTotalSalario {
            get {
                return this.fTotalSalarioField;
            }
            set {
                if ((this.fTotalSalarioField.Equals(value) != true)) {
                    this.fTotalSalarioField = value;
                    this.RaisePropertyChanged("fTotalSalario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ServicioEmpleado.WCFEmpleado")]
    public interface WCFEmpleado {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WCFEmpleado/DoWork", ReplyAction="urn:WCFEmpleado/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WCFEmpleado/DoWork", ReplyAction="urn:WCFEmpleado/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WCFEmpleado/GuardaEMpleados", ReplyAction="urn:WCFEmpleado/GuardaEMpleadosResponse")]
        int GuardaEMpleados(PruebaC.ServicioEmpleado.DTOEmpleado datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WCFEmpleado/GuardaEMpleados", ReplyAction="urn:WCFEmpleado/GuardaEMpleadosResponse")]
        System.Threading.Tasks.Task<int> GuardaEMpleadosAsync(PruebaC.ServicioEmpleado.DTOEmpleado datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WCFEmpleado/ConsultaEmpleado", ReplyAction="urn:WCFEmpleado/ConsultaEmpleadoResponse")]
        PruebaC.ServicioEmpleado.DTOEmpleado ConsultaEmpleado(int IdEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WCFEmpleado/ConsultaEmpleado", ReplyAction="urn:WCFEmpleado/ConsultaEmpleadoResponse")]
        System.Threading.Tasks.Task<PruebaC.ServicioEmpleado.DTOEmpleado> ConsultaEmpleadoAsync(int IdEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WCFEmpleado/GuardaEntregasEMpleados", ReplyAction="urn:WCFEmpleado/GuardaEntregasEMpleadosResponse")]
        int GuardaEntregasEMpleados(PruebaC.ServicioEmpleado.DTOEmpleado datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WCFEmpleado/GuardaEntregasEMpleados", ReplyAction="urn:WCFEmpleado/GuardaEntregasEMpleadosResponse")]
        System.Threading.Tasks.Task<int> GuardaEntregasEMpleadosAsync(PruebaC.ServicioEmpleado.DTOEmpleado datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WCFEmpleado/ConsultaNominao", ReplyAction="urn:WCFEmpleado/ConsultaNominaoResponse")]
        PruebaC.ServicioEmpleado.DTOEmpleado[] ConsultaNominao(PruebaC.ServicioEmpleado.DTOEmpleado Datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WCFEmpleado/ConsultaNominao", ReplyAction="urn:WCFEmpleado/ConsultaNominaoResponse")]
        System.Threading.Tasks.Task<PruebaC.ServicioEmpleado.DTOEmpleado[]> ConsultaNominaoAsync(PruebaC.ServicioEmpleado.DTOEmpleado Datos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WCFEmpleadoChannel : PruebaC.ServicioEmpleado.WCFEmpleado, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFEmpleadoClient : System.ServiceModel.ClientBase<PruebaC.ServicioEmpleado.WCFEmpleado>, PruebaC.ServicioEmpleado.WCFEmpleado {
        
        public WCFEmpleadoClient() {
        }
        
        public WCFEmpleadoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFEmpleadoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFEmpleadoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFEmpleadoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public int GuardaEMpleados(PruebaC.ServicioEmpleado.DTOEmpleado datos) {
            return base.Channel.GuardaEMpleados(datos);
        }
        
        public System.Threading.Tasks.Task<int> GuardaEMpleadosAsync(PruebaC.ServicioEmpleado.DTOEmpleado datos) {
            return base.Channel.GuardaEMpleadosAsync(datos);
        }
        
        public PruebaC.ServicioEmpleado.DTOEmpleado ConsultaEmpleado(int IdEmpleado) {
            return base.Channel.ConsultaEmpleado(IdEmpleado);
        }
        
        public System.Threading.Tasks.Task<PruebaC.ServicioEmpleado.DTOEmpleado> ConsultaEmpleadoAsync(int IdEmpleado) {
            return base.Channel.ConsultaEmpleadoAsync(IdEmpleado);
        }
        
        public int GuardaEntregasEMpleados(PruebaC.ServicioEmpleado.DTOEmpleado datos) {
            return base.Channel.GuardaEntregasEMpleados(datos);
        }
        
        public System.Threading.Tasks.Task<int> GuardaEntregasEMpleadosAsync(PruebaC.ServicioEmpleado.DTOEmpleado datos) {
            return base.Channel.GuardaEntregasEMpleadosAsync(datos);
        }
        
        public PruebaC.ServicioEmpleado.DTOEmpleado[] ConsultaNominao(PruebaC.ServicioEmpleado.DTOEmpleado Datos) {
            return base.Channel.ConsultaNominao(Datos);
        }
        
        public System.Threading.Tasks.Task<PruebaC.ServicioEmpleado.DTOEmpleado[]> ConsultaNominaoAsync(PruebaC.ServicioEmpleado.DTOEmpleado Datos) {
            return base.Channel.ConsultaNominaoAsync(Datos);
        }
    }
}
