//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manag.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agenda
    {
        public long IdAgenda { get; set; }
        public Nullable<int> IdClinica { get; set; }
        public Nullable<int> IdPaciente { get; set; }
        public Nullable<int> IdDoctor { get; set; }
        public Nullable<System.DateTime> FechaCita { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public string Usuario { get; set; }
    }
}
