//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manag.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        public long IdConsulta { get; set; }
        public long IdPaciente { get; set; }
        public Nullable<long> IdAgenda { get; set; }
        public string Motivo { get; set; }
        public string PadecimientoActual { get; set; }
        public string EnConsulta { get; set; }
        public string PlanTerapeutico { get; set; }
        public Nullable<System.DateTime> FechaConsulta { get; set; }
    }
}
