//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manag.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtEstatus
    {
        public int IdEstatus { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Inactivo { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public string Usuario { get; set; }
    }
}
