//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manag.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class clinicaEntities : DbContext
    {
        public clinicaEntities()
            : base("name=clinicaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agenda> Agenda { get; set; }
        public virtual DbSet<Consulta> Consulta { get; set; }
        public virtual DbSet<CtClinica> CtClinica { get; set; }
        public virtual DbSet<CtConsultorio> CtConsultorio { get; set; }
        public virtual DbSet<CtEquipoTrabajo> CtEquipoTrabajo { get; set; }
        public virtual DbSet<CtEspecialidad> CtEspecialidad { get; set; }
        public virtual DbSet<CtEstatus> CtEstatus { get; set; }
        public virtual DbSet<CtInformacion> CtInformacion { get; set; }
        public virtual DbSet<CtPregunta> CtPregunta { get; set; }
        public virtual DbSet<CtTipoEnConsulta> CtTipoEnConsulta { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<Puesto> Puesto { get; set; }
        public virtual DbSet<Rel_Consulta_Diagnostico> Rel_Consulta_Diagnostico { get; set; }
        public virtual DbSet<Rel_Consulta_Fotos> Rel_Consulta_Fotos { get; set; }
        public virtual DbSet<Rel_EnConsulta_Pregunta> Rel_EnConsulta_Pregunta { get; set; }
        public virtual DbSet<Rel_EnConsulta_Pregunta_Respuesta> Rel_EnConsulta_Pregunta_Respuesta { get; set; }
        public virtual DbSet<Rel_Especialidad_Imagen> Rel_Especialidad_Imagen { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual ObjectResult<Nullable<decimal>> Agenda_C_Nueva(Nullable<int> idPaciente, Nullable<int> idDoctor, Nullable<System.DateTime> fechaCita, string usuario, Nullable<int> idEstatus, Nullable<int> idClinica)
        {
            var idPacienteParameter = idPaciente.HasValue ?
                new ObjectParameter("IdPaciente", idPaciente) :
                new ObjectParameter("IdPaciente", typeof(int));
    
            var idDoctorParameter = idDoctor.HasValue ?
                new ObjectParameter("IdDoctor", idDoctor) :
                new ObjectParameter("IdDoctor", typeof(int));
    
            var fechaCitaParameter = fechaCita.HasValue ?
                new ObjectParameter("FechaCita", fechaCita) :
                new ObjectParameter("FechaCita", typeof(System.DateTime));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var idEstatusParameter = idEstatus.HasValue ?
                new ObjectParameter("IdEstatus", idEstatus) :
                new ObjectParameter("IdEstatus", typeof(int));
    
            var idClinicaParameter = idClinica.HasValue ?
                new ObjectParameter("IdClinica", idClinica) :
                new ObjectParameter("IdClinica", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Agenda_C_Nueva", idPacienteParameter, idDoctorParameter, fechaCitaParameter, usuarioParameter, idEstatusParameter, idClinicaParameter);
        }
    
        public virtual ObjectResult<Agenda_R_Fecha_Result> Agenda_R_Fecha(Nullable<int> idPaciente, Nullable<int> idDoctor, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<int> idClinica)
        {
            var idPacienteParameter = idPaciente.HasValue ?
                new ObjectParameter("IdPaciente", idPaciente) :
                new ObjectParameter("IdPaciente", typeof(int));
    
            var idDoctorParameter = idDoctor.HasValue ?
                new ObjectParameter("IdDoctor", idDoctor) :
                new ObjectParameter("IdDoctor", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var idClinicaParameter = idClinica.HasValue ?
                new ObjectParameter("IdClinica", idClinica) :
                new ObjectParameter("IdClinica", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Agenda_R_Fecha_Result>("Agenda_R_Fecha", idPacienteParameter, idDoctorParameter, fechaInicioParameter, fechaFinParameter, idClinicaParameter);
        }
    
        public virtual ObjectResult<Agenda_R_Id_Result> Agenda_R_Id(Nullable<int> idAgenda)
        {
            var idAgendaParameter = idAgenda.HasValue ?
                new ObjectParameter("IdAgenda", idAgenda) :
                new ObjectParameter("IdAgenda", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Agenda_R_Id_Result>("Agenda_R_Id", idAgendaParameter);
        }
    
        public virtual int Agenda_U_Cita(Nullable<long> idAgenda, Nullable<int> idPaciente, Nullable<int> idDoctor, Nullable<System.DateTime> fechaCita, string usuario, Nullable<int> idEstatus)
        {
            var idAgendaParameter = idAgenda.HasValue ?
                new ObjectParameter("IdAgenda", idAgenda) :
                new ObjectParameter("IdAgenda", typeof(long));
    
            var idPacienteParameter = idPaciente.HasValue ?
                new ObjectParameter("IdPaciente", idPaciente) :
                new ObjectParameter("IdPaciente", typeof(int));
    
            var idDoctorParameter = idDoctor.HasValue ?
                new ObjectParameter("IdDoctor", idDoctor) :
                new ObjectParameter("IdDoctor", typeof(int));
    
            var fechaCitaParameter = fechaCita.HasValue ?
                new ObjectParameter("FechaCita", fechaCita) :
                new ObjectParameter("FechaCita", typeof(System.DateTime));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var idEstatusParameter = idEstatus.HasValue ?
                new ObjectParameter("IdEstatus", idEstatus) :
                new ObjectParameter("IdEstatus", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Agenda_U_Cita", idAgendaParameter, idPacienteParameter, idDoctorParameter, fechaCitaParameter, usuarioParameter, idEstatusParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Agrega_C_Imagen(Nullable<long> idConsulta, byte[] imagen, string nombreImagen)
        {
            var idConsultaParameter = idConsulta.HasValue ?
                new ObjectParameter("IdConsulta", idConsulta) :
                new ObjectParameter("IdConsulta", typeof(long));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("Imagen", imagen) :
                new ObjectParameter("Imagen", typeof(byte[]));
    
            var nombreImagenParameter = nombreImagen != null ?
                new ObjectParameter("NombreImagen", nombreImagen) :
                new ObjectParameter("NombreImagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Agrega_C_Imagen", idConsultaParameter, imagenParameter, nombreImagenParameter);
        }
    
        public virtual ObjectResult<Clinica_R_All_Result> Clinica_R_All()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Clinica_R_All_Result>("Clinica_R_All");
        }
    
        public virtual ObjectResult<Consula_R_Filtro_Result> Consula_R_Filtro(Nullable<int> idPaciente, Nullable<int> idDoctor, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var idPacienteParameter = idPaciente.HasValue ?
                new ObjectParameter("IdPaciente", idPaciente) :
                new ObjectParameter("IdPaciente", typeof(int));
    
            var idDoctorParameter = idDoctor.HasValue ?
                new ObjectParameter("IdDoctor", idDoctor) :
                new ObjectParameter("IdDoctor", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consula_R_Filtro_Result>("Consula_R_Filtro", idPacienteParameter, idDoctorParameter, fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<Consula_R_PorId_Result> Consula_R_PorId(Nullable<long> idConsulta)
        {
            var idConsultaParameter = idConsulta.HasValue ?
                new ObjectParameter("IdConsulta", idConsulta) :
                new ObjectParameter("IdConsulta", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consula_R_PorId_Result>("Consula_R_PorId", idConsultaParameter);
        }
    
        public virtual ObjectResult<Consula_R_PorIdPacientePaciente_Result> Consula_R_PorIdPacientePaciente(Nullable<long> idPaciente)
        {
            var idPacienteParameter = idPaciente.HasValue ?
                new ObjectParameter("IdPaciente", idPaciente) :
                new ObjectParameter("IdPaciente", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consula_R_PorIdPacientePaciente_Result>("Consula_R_PorIdPacientePaciente", idPacienteParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Consulta_C_Datos(Nullable<long> idPaciente, Nullable<long> idAgenda, string motivo, string padecimientoActual, string planTerapeutico, string xMLEnConsulta, string xMLDiagnosticos, string enConsulta)
        {
            var idPacienteParameter = idPaciente.HasValue ?
                new ObjectParameter("IdPaciente", idPaciente) :
                new ObjectParameter("IdPaciente", typeof(long));
    
            var idAgendaParameter = idAgenda.HasValue ?
                new ObjectParameter("IdAgenda", idAgenda) :
                new ObjectParameter("IdAgenda", typeof(long));
    
            var motivoParameter = motivo != null ?
                new ObjectParameter("Motivo", motivo) :
                new ObjectParameter("Motivo", typeof(string));
    
            var padecimientoActualParameter = padecimientoActual != null ?
                new ObjectParameter("PadecimientoActual", padecimientoActual) :
                new ObjectParameter("PadecimientoActual", typeof(string));
    
            var planTerapeuticoParameter = planTerapeutico != null ?
                new ObjectParameter("PlanTerapeutico", planTerapeutico) :
                new ObjectParameter("PlanTerapeutico", typeof(string));
    
            var xMLEnConsultaParameter = xMLEnConsulta != null ?
                new ObjectParameter("XMLEnConsulta", xMLEnConsulta) :
                new ObjectParameter("XMLEnConsulta", typeof(string));
    
            var xMLDiagnosticosParameter = xMLDiagnosticos != null ?
                new ObjectParameter("XMLDiagnosticos", xMLDiagnosticos) :
                new ObjectParameter("XMLDiagnosticos", typeof(string));
    
            var enConsultaParameter = enConsulta != null ?
                new ObjectParameter("EnConsulta", enConsulta) :
                new ObjectParameter("EnConsulta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Consulta_C_Datos", idPacienteParameter, idAgendaParameter, motivoParameter, padecimientoActualParameter, planTerapeuticoParameter, xMLEnConsultaParameter, xMLDiagnosticosParameter, enConsultaParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> Consulta_U_Datos(Nullable<long> idPaciente, Nullable<long> idAgenda, string motivo, string padecimientoActual, string planTerapeutico, string xMLEnConsulta, string xMLDiagnosticos, string enConsulta, Nullable<long> idConsulta)
        {
            var idPacienteParameter = idPaciente.HasValue ?
                new ObjectParameter("IdPaciente", idPaciente) :
                new ObjectParameter("IdPaciente", typeof(long));
    
            var idAgendaParameter = idAgenda.HasValue ?
                new ObjectParameter("IdAgenda", idAgenda) :
                new ObjectParameter("IdAgenda", typeof(long));
    
            var motivoParameter = motivo != null ?
                new ObjectParameter("Motivo", motivo) :
                new ObjectParameter("Motivo", typeof(string));
    
            var padecimientoActualParameter = padecimientoActual != null ?
                new ObjectParameter("PadecimientoActual", padecimientoActual) :
                new ObjectParameter("PadecimientoActual", typeof(string));
    
            var planTerapeuticoParameter = planTerapeutico != null ?
                new ObjectParameter("PlanTerapeutico", planTerapeutico) :
                new ObjectParameter("PlanTerapeutico", typeof(string));
    
            var xMLEnConsultaParameter = xMLEnConsulta != null ?
                new ObjectParameter("XMLEnConsulta", xMLEnConsulta) :
                new ObjectParameter("XMLEnConsulta", typeof(string));
    
            var xMLDiagnosticosParameter = xMLDiagnosticos != null ?
                new ObjectParameter("XMLDiagnosticos", xMLDiagnosticos) :
                new ObjectParameter("XMLDiagnosticos", typeof(string));
    
            var enConsultaParameter = enConsulta != null ?
                new ObjectParameter("EnConsulta", enConsulta) :
                new ObjectParameter("EnConsulta", typeof(string));
    
            var idConsultaParameter = idConsulta.HasValue ?
                new ObjectParameter("IdConsulta", idConsulta) :
                new ObjectParameter("IdConsulta", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("Consulta_U_Datos", idPacienteParameter, idAgendaParameter, motivoParameter, padecimientoActualParameter, planTerapeuticoParameter, xMLEnConsultaParameter, xMLDiagnosticosParameter, enConsultaParameter, idConsultaParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Consultorio_C_Registro(Nullable<int> idClinica, Nullable<int> idEspecialidad, string descripcion, string usuario)
        {
            var idClinicaParameter = idClinica.HasValue ?
                new ObjectParameter("IdClinica", idClinica) :
                new ObjectParameter("IdClinica", typeof(int));
    
            var idEspecialidadParameter = idEspecialidad.HasValue ?
                new ObjectParameter("IdEspecialidad", idEspecialidad) :
                new ObjectParameter("IdEspecialidad", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Consultorio_C_Registro", idClinicaParameter, idEspecialidadParameter, descripcionParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> CtClinica_C_GuardaRegistro(string descripcion, string usuario)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("CtClinica_C_GuardaRegistro", descripcionParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<CtClinica_R_Datos_Result> CtClinica_R_Datos(string usuario, string ip)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var ipParameter = ip != null ?
                new ObjectParameter("Ip", ip) :
                new ObjectParameter("Ip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CtClinica_R_Datos_Result>("CtClinica_R_Datos", usuarioParameter, ipParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CtCliniva_U_Registro(Nullable<int> idClinica, string clinica, string usuario)
        {
            var idClinicaParameter = idClinica.HasValue ?
                new ObjectParameter("IdClinica", idClinica) :
                new ObjectParameter("IdClinica", typeof(int));
    
            var clinicaParameter = clinica != null ?
                new ObjectParameter("Clinica", clinica) :
                new ObjectParameter("Clinica", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CtCliniva_U_Registro", idClinicaParameter, clinicaParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<CtConsultorio_R_DATOS_Result> CtConsultorio_R_DATOS(string usuario, string ip)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var ipParameter = ip != null ?
                new ObjectParameter("Ip", ip) :
                new ObjectParameter("Ip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CtConsultorio_R_DATOS_Result>("CtConsultorio_R_DATOS", usuarioParameter, ipParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CtConsultorio_U_REGISTRO(Nullable<int> idConsultorio, Nullable<int> idClinica, Nullable<int> idEspecialidad, string descripcion, string usuario)
        {
            var idConsultorioParameter = idConsultorio.HasValue ?
                new ObjectParameter("IdConsultorio", idConsultorio) :
                new ObjectParameter("IdConsultorio", typeof(int));
    
            var idClinicaParameter = idClinica.HasValue ?
                new ObjectParameter("IdClinica", idClinica) :
                new ObjectParameter("IdClinica", typeof(int));
    
            var idEspecialidadParameter = idEspecialidad.HasValue ?
                new ObjectParameter("IdEspecialidad", idEspecialidad) :
                new ObjectParameter("IdEspecialidad", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CtConsultorio_U_REGISTRO", idConsultorioParameter, idClinicaParameter, idEspecialidadParameter, descripcionParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> CtEquipoTrabajo_C_Datos(string nombre, string descripcion, string horario, byte[] foto)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var horarioParameter = horario != null ?
                new ObjectParameter("Horario", horario) :
                new ObjectParameter("Horario", typeof(string));
    
            var fotoParameter = foto != null ?
                new ObjectParameter("Foto", foto) :
                new ObjectParameter("Foto", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("CtEquipoTrabajo_C_Datos", nombreParameter, descripcionParameter, horarioParameter, fotoParameter);
        }
    
        public virtual ObjectResult<CtEquipoTrabajo_R_Datos_Result> CtEquipoTrabajo_R_Datos(string usuario, string ip)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var ipParameter = ip != null ?
                new ObjectParameter("Ip", ip) :
                new ObjectParameter("Ip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CtEquipoTrabajo_R_Datos_Result>("CtEquipoTrabajo_R_Datos", usuarioParameter, ipParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CtEquipoTrabajo_u_Datos(Nullable<int> idDoctor, string nombre, string descripcion, string horario, byte[] foto)
        {
            var idDoctorParameter = idDoctor.HasValue ?
                new ObjectParameter("IdDoctor", idDoctor) :
                new ObjectParameter("IdDoctor", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var horarioParameter = horario != null ?
                new ObjectParameter("Horario", horario) :
                new ObjectParameter("Horario", typeof(string));
    
            var fotoParameter = foto != null ?
                new ObjectParameter("Foto", foto) :
                new ObjectParameter("Foto", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CtEquipoTrabajo_u_Datos", idDoctorParameter, nombreParameter, descripcionParameter, horarioParameter, fotoParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> CtEspecialidad_C_REGISTRO(string idClinica, string descripcion, string usuario)
        {
            var idClinicaParameter = idClinica != null ?
                new ObjectParameter("IdClinica", idClinica) :
                new ObjectParameter("IdClinica", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("CtEspecialidad_C_REGISTRO", idClinicaParameter, descripcionParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<CtEspecialidad_R_Datos_Result> CtEspecialidad_R_Datos(string usuario, string ip)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var ipParameter = ip != null ?
                new ObjectParameter("Ip", ip) :
                new ObjectParameter("Ip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CtEspecialidad_R_Datos_Result>("CtEspecialidad_R_Datos", usuarioParameter, ipParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CTEspecialidad_U_REGISTRO(Nullable<int> idClinica, Nullable<int> idEspecialidad, string descripcion, string usuario)
        {
            var idClinicaParameter = idClinica.HasValue ?
                new ObjectParameter("IdClinica", idClinica) :
                new ObjectParameter("IdClinica", typeof(int));
    
            var idEspecialidadParameter = idEspecialidad.HasValue ?
                new ObjectParameter("IdEspecialidad", idEspecialidad) :
                new ObjectParameter("IdEspecialidad", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CTEspecialidad_U_REGISTRO", idClinicaParameter, idEspecialidadParameter, descripcionParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> CtEstatus_C_Registro(string descripcion, string usuario)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("CtEstatus_C_Registro", descripcionParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<CtEstatus_R_Datos_Result> CtEstatus_R_Datos(string usuario, string ip)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var ipParameter = ip != null ?
                new ObjectParameter("Ip", ip) :
                new ObjectParameter("Ip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CtEstatus_R_Datos_Result>("CtEstatus_R_Datos", usuarioParameter, ipParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CtEstatus_U_Registro(Nullable<int> idEstatus, string estatus, string usuario)
        {
            var idEstatusParameter = idEstatus.HasValue ?
                new ObjectParameter("IdEstatus", idEstatus) :
                new ObjectParameter("IdEstatus", typeof(int));
    
            var estatusParameter = estatus != null ?
                new ObjectParameter("Estatus", estatus) :
                new ObjectParameter("Estatus", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CtEstatus_U_Registro", idEstatusParameter, estatusParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> CtInformacion_C_Datos(string quienes, string mision, string vision)
        {
            var quienesParameter = quienes != null ?
                new ObjectParameter("Quienes", quienes) :
                new ObjectParameter("Quienes", typeof(string));
    
            var misionParameter = mision != null ?
                new ObjectParameter("Mision", mision) :
                new ObjectParameter("Mision", typeof(string));
    
            var visionParameter = vision != null ?
                new ObjectParameter("Vision", vision) :
                new ObjectParameter("Vision", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("CtInformacion_C_Datos", quienesParameter, misionParameter, visionParameter);
        }
    
        public virtual ObjectResult<CtInformacion_R_DATOS_Result> CtInformacion_R_DATOS(string usuario, string ip)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var ipParameter = ip != null ?
                new ObjectParameter("Ip", ip) :
                new ObjectParameter("Ip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CtInformacion_R_DATOS_Result>("CtInformacion_R_DATOS", usuarioParameter, ipParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CtInformacion_U_Datos(Nullable<int> idInformacion, string quienes, string mision, string vision)
        {
            var idInformacionParameter = idInformacion.HasValue ?
                new ObjectParameter("IdInformacion", idInformacion) :
                new ObjectParameter("IdInformacion", typeof(int));
    
            var quienesParameter = quienes != null ?
                new ObjectParameter("Quienes", quienes) :
                new ObjectParameter("Quienes", typeof(string));
    
            var misionParameter = mision != null ?
                new ObjectParameter("Mision", mision) :
                new ObjectParameter("Mision", typeof(string));
    
            var visionParameter = vision != null ?
                new ObjectParameter("Vision", vision) :
                new ObjectParameter("Vision", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CtInformacion_U_Datos", idInformacionParameter, quienesParameter, misionParameter, visionParameter);
        }
    
        public virtual int CtPaciente_C_GuardaRegistro(string nombre, string paterno, string materno, string usuario)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var paternoParameter = paterno != null ?
                new ObjectParameter("Paterno", paterno) :
                new ObjectParameter("Paterno", typeof(string));
    
            var maternoParameter = materno != null ?
                new ObjectParameter("Materno", materno) :
                new ObjectParameter("Materno", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CtPaciente_C_GuardaRegistro", nombreParameter, paternoParameter, maternoParameter, usuarioParameter);
        }
    
        public virtual int CtUsuario_C_GuardaRegistro(string loginName, string password, string nombre, string paterno, string materno, string usuario, Nullable<int> idPuesto)
        {
            var loginNameParameter = loginName != null ?
                new ObjectParameter("LoginName", loginName) :
                new ObjectParameter("LoginName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var paternoParameter = paterno != null ?
                new ObjectParameter("Paterno", paterno) :
                new ObjectParameter("Paterno", typeof(string));
    
            var maternoParameter = materno != null ?
                new ObjectParameter("Materno", materno) :
                new ObjectParameter("Materno", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var idPuestoParameter = idPuesto.HasValue ?
                new ObjectParameter("IdPuesto", idPuesto) :
                new ObjectParameter("IdPuesto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CtUsuario_C_GuardaRegistro", loginNameParameter, passwordParameter, nombreParameter, paternoParameter, maternoParameter, usuarioParameter, idPuestoParameter);
        }
    
        public virtual ObjectResult<Doctor_R_All_Result> Doctor_R_All()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Doctor_R_All_Result>("Doctor_R_All");
        }
    
        public virtual ObjectResult<Nullable<decimal>> Especialidad_C_Imagen(Nullable<int> idEspecialidad, Nullable<int> consecutivo, string nombre, byte[] imagen)
        {
            var idEspecialidadParameter = idEspecialidad.HasValue ?
                new ObjectParameter("IdEspecialidad", idEspecialidad) :
                new ObjectParameter("IdEspecialidad", typeof(int));
    
            var consecutivoParameter = consecutivo.HasValue ?
                new ObjectParameter("Consecutivo", consecutivo) :
                new ObjectParameter("Consecutivo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("Imagen", imagen) :
                new ObjectParameter("Imagen", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Especialidad_C_Imagen", idEspecialidadParameter, consecutivoParameter, nombreParameter, imagenParameter);
        }
    
        public virtual int Especialidad_C_Parrafos(Nullable<int> idEspecialidad, string parrafo1, string parrafo2, string parrafo3)
        {
            var idEspecialidadParameter = idEspecialidad.HasValue ?
                new ObjectParameter("IdEspecialidad", idEspecialidad) :
                new ObjectParameter("IdEspecialidad", typeof(int));
    
            var parrafo1Parameter = parrafo1 != null ?
                new ObjectParameter("Parrafo1", parrafo1) :
                new ObjectParameter("Parrafo1", typeof(string));
    
            var parrafo2Parameter = parrafo2 != null ?
                new ObjectParameter("Parrafo2", parrafo2) :
                new ObjectParameter("Parrafo2", typeof(string));
    
            var parrafo3Parameter = parrafo3 != null ?
                new ObjectParameter("Parrafo3", parrafo3) :
                new ObjectParameter("Parrafo3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Especialidad_C_Parrafos", idEspecialidadParameter, parrafo1Parameter, parrafo2Parameter, parrafo3Parameter);
        }
    
        public virtual ObjectResult<Especialidad_R_ParrafosImagenes_Result> Especialidad_R_ParrafosImagenes(Nullable<int> idEspecialidad)
        {
            var idEspecialidadParameter = idEspecialidad.HasValue ?
                new ObjectParameter("IdEspecialidad", idEspecialidad) :
                new ObjectParameter("IdEspecialidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Especialidad_R_ParrafosImagenes_Result>("Especialidad_R_ParrafosImagenes", idEspecialidadParameter);
        }
    
        public virtual ObjectResult<Especialidad_R_ParrafosImagenesPrincipal_Result> Especialidad_R_ParrafosImagenesPrincipal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Especialidad_R_ParrafosImagenesPrincipal_Result>("Especialidad_R_ParrafosImagenesPrincipal");
        }
    
        public virtual ObjectResult<Imagen_R_PorAgenda_Result> Imagen_R_PorAgenda(Nullable<long> idAgenda, Nullable<int> idDoctor)
        {
            var idAgendaParameter = idAgenda.HasValue ?
                new ObjectParameter("IdAgenda", idAgenda) :
                new ObjectParameter("IdAgenda", typeof(long));
    
            var idDoctorParameter = idDoctor.HasValue ?
                new ObjectParameter("IdDoctor", idDoctor) :
                new ObjectParameter("IdDoctor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Imagen_R_PorAgenda_Result>("Imagen_R_PorAgenda", idAgendaParameter, idDoctorParameter);
        }
    
        public virtual ObjectResult<Imagen_R_PorConsulta_Result> Imagen_R_PorConsulta(Nullable<long> idConsulta)
        {
            var idConsultaParameter = idConsulta.HasValue ?
                new ObjectParameter("IdConsulta", idConsulta) :
                new ObjectParameter("IdConsulta", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Imagen_R_PorConsulta_Result>("Imagen_R_PorConsulta", idConsultaParameter);
        }
    
        public virtual ObjectResult<Imagen_R_PorIdConsulta_Result> Imagen_R_PorIdConsulta(Nullable<long> idConsulta, Nullable<int> idDoctor)
        {
            var idConsultaParameter = idConsulta.HasValue ?
                new ObjectParameter("IdConsulta", idConsulta) :
                new ObjectParameter("IdConsulta", typeof(long));
    
            var idDoctorParameter = idDoctor.HasValue ?
                new ObjectParameter("IdDoctor", idDoctor) :
                new ObjectParameter("IdDoctor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Imagen_R_PorIdConsulta_Result>("Imagen_R_PorIdConsulta", idConsultaParameter, idDoctorParameter);
        }
    
        public virtual ObjectResult<Informacion_R_Datos_Result> Informacion_R_Datos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Informacion_R_Datos_Result>("Informacion_R_Datos");
        }
    
        public virtual ObjectResult<Nullable<decimal>> Paciente_C_REGISTRO(string nombre, string paterno, string materno, string usuario, Nullable<System.DateTime> fechaNacimiento, string temperaturaCorporal, string peso, Nullable<int> edad, string numeroTelefono, string pulso, string presionArterial)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var paternoParameter = paterno != null ?
                new ObjectParameter("Paterno", paterno) :
                new ObjectParameter("Paterno", typeof(string));
    
            var maternoParameter = materno != null ?
                new ObjectParameter("Materno", materno) :
                new ObjectParameter("Materno", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(System.DateTime));
    
            var temperaturaCorporalParameter = temperaturaCorporal != null ?
                new ObjectParameter("TemperaturaCorporal", temperaturaCorporal) :
                new ObjectParameter("TemperaturaCorporal", typeof(string));
    
            var pesoParameter = peso != null ?
                new ObjectParameter("Peso", peso) :
                new ObjectParameter("Peso", typeof(string));
    
            var edadParameter = edad.HasValue ?
                new ObjectParameter("Edad", edad) :
                new ObjectParameter("Edad", typeof(int));
    
            var numeroTelefonoParameter = numeroTelefono != null ?
                new ObjectParameter("NumeroTelefono", numeroTelefono) :
                new ObjectParameter("NumeroTelefono", typeof(string));
    
            var pulsoParameter = pulso != null ?
                new ObjectParameter("Pulso", pulso) :
                new ObjectParameter("Pulso", typeof(string));
    
            var presionArterialParameter = presionArterial != null ?
                new ObjectParameter("PresionArterial", presionArterial) :
                new ObjectParameter("PresionArterial", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Paciente_C_REGISTRO", nombreParameter, paternoParameter, maternoParameter, usuarioParameter, fechaNacimientoParameter, temperaturaCorporalParameter, pesoParameter, edadParameter, numeroTelefonoParameter, pulsoParameter, presionArterialParameter);
        }
    
        public virtual ObjectResult<Paciente_R_All_Result> Paciente_R_All()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Paciente_R_All_Result>("Paciente_R_All");
        }
    
        public virtual ObjectResult<Paciente_R_DATOS_Result> Paciente_R_DATOS(string usuario, string ip)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var ipParameter = ip != null ?
                new ObjectParameter("Ip", ip) :
                new ObjectParameter("Ip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Paciente_R_DATOS_Result>("Paciente_R_DATOS", usuarioParameter, ipParameter);
        }
    
        public virtual ObjectResult<Paciente_R_HistoriaClinica_Result> Paciente_R_HistoriaClinica(Nullable<long> idPaciente)
        {
            var idPacienteParameter = idPaciente.HasValue ?
                new ObjectParameter("IdPaciente", idPaciente) :
                new ObjectParameter("IdPaciente", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Paciente_R_HistoriaClinica_Result>("Paciente_R_HistoriaClinica", idPacienteParameter);
        }
    
        public virtual int Paciente_U_HistoriaClinica(Nullable<long> idPaciente, string historiaClinica)
        {
            var idPacienteParameter = idPaciente.HasValue ?
                new ObjectParameter("IdPaciente", idPaciente) :
                new ObjectParameter("IdPaciente", typeof(long));
    
            var historiaClinicaParameter = historiaClinica != null ?
                new ObjectParameter("HistoriaClinica", historiaClinica) :
                new ObjectParameter("HistoriaClinica", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Paciente_U_HistoriaClinica", idPacienteParameter, historiaClinicaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Paciente_U_Registro(Nullable<int> idPaciente, string nombre, string paterno, string materno, string usuario, Nullable<System.DateTime> fechaNacimiento, string temperaturaCorporal, string peso, Nullable<int> edad, string numeroTelefono, string pulso, string presionArterial)
        {
            var idPacienteParameter = idPaciente.HasValue ?
                new ObjectParameter("IdPaciente", idPaciente) :
                new ObjectParameter("IdPaciente", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var paternoParameter = paterno != null ?
                new ObjectParameter("Paterno", paterno) :
                new ObjectParameter("Paterno", typeof(string));
    
            var maternoParameter = materno != null ?
                new ObjectParameter("Materno", materno) :
                new ObjectParameter("Materno", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(System.DateTime));
    
            var temperaturaCorporalParameter = temperaturaCorporal != null ?
                new ObjectParameter("TemperaturaCorporal", temperaturaCorporal) :
                new ObjectParameter("TemperaturaCorporal", typeof(string));
    
            var pesoParameter = peso != null ?
                new ObjectParameter("Peso", peso) :
                new ObjectParameter("Peso", typeof(string));
    
            var edadParameter = edad.HasValue ?
                new ObjectParameter("Edad", edad) :
                new ObjectParameter("Edad", typeof(int));
    
            var numeroTelefonoParameter = numeroTelefono != null ?
                new ObjectParameter("NumeroTelefono", numeroTelefono) :
                new ObjectParameter("NumeroTelefono", typeof(string));
    
            var pulsoParameter = pulso != null ?
                new ObjectParameter("Pulso", pulso) :
                new ObjectParameter("Pulso", typeof(string));
    
            var presionArterialParameter = presionArterial != null ?
                new ObjectParameter("PresionArterial", presionArterial) :
                new ObjectParameter("PresionArterial", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Paciente_U_Registro", idPacienteParameter, nombreParameter, paternoParameter, maternoParameter, usuarioParameter, fechaNacimientoParameter, temperaturaCorporalParameter, pesoParameter, edadParameter, numeroTelefonoParameter, pulsoParameter, presionArterialParameter);
        }
    
        public virtual ObjectResult<Pregunta_R_PorTipoEnConsulta_Result> Pregunta_R_PorTipoEnConsulta(Nullable<int> idTipoEnConsulta)
        {
            var idTipoEnConsultaParameter = idTipoEnConsulta.HasValue ?
                new ObjectParameter("IdTipoEnConsulta", idTipoEnConsulta) :
                new ObjectParameter("IdTipoEnConsulta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pregunta_R_PorTipoEnConsulta_Result>("Pregunta_R_PorTipoEnConsulta", idTipoEnConsultaParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> PUESTO_C_REGISTRO(string descripcion, string usuario)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("PUESTO_C_REGISTRO", descripcionParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<Puesto_R_Datos_Result> Puesto_R_Datos(string usuario, string ip)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var ipParameter = ip != null ?
                new ObjectParameter("Ip", ip) :
                new ObjectParameter("Ip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Puesto_R_Datos_Result>("Puesto_R_Datos", usuarioParameter, ipParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> PUESTO_U_REGISTRO(Nullable<int> idPuesto, string puesto, string usuario)
        {
            var idPuestoParameter = idPuesto.HasValue ?
                new ObjectParameter("IdPuesto", idPuesto) :
                new ObjectParameter("IdPuesto", typeof(int));
    
            var puestoParameter = puesto != null ?
                new ObjectParameter("Puesto", puesto) :
                new ObjectParameter("Puesto", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PUESTO_U_REGISTRO", idPuestoParameter, puestoParameter, usuarioParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<TipoEnConsulta_R_All_Result> TipoEnConsulta_R_All()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TipoEnConsulta_R_All_Result>("TipoEnConsulta_R_All");
        }
    
        public virtual ObjectResult<Nullable<decimal>> USUARIO_C_REGISTRO(string loginName, string password, string nombre, string paterno, string materno, Nullable<int> idPuesto, string usuario, Nullable<int> idClinica, Nullable<int> idEspecialidad, byte[] foto)
        {
            var loginNameParameter = loginName != null ?
                new ObjectParameter("LoginName", loginName) :
                new ObjectParameter("LoginName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var paternoParameter = paterno != null ?
                new ObjectParameter("Paterno", paterno) :
                new ObjectParameter("Paterno", typeof(string));
    
            var maternoParameter = materno != null ?
                new ObjectParameter("Materno", materno) :
                new ObjectParameter("Materno", typeof(string));
    
            var idPuestoParameter = idPuesto.HasValue ?
                new ObjectParameter("IdPuesto", idPuesto) :
                new ObjectParameter("IdPuesto", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var idClinicaParameter = idClinica.HasValue ?
                new ObjectParameter("IdClinica", idClinica) :
                new ObjectParameter("IdClinica", typeof(int));
    
            var idEspecialidadParameter = idEspecialidad.HasValue ?
                new ObjectParameter("IdEspecialidad", idEspecialidad) :
                new ObjectParameter("IdEspecialidad", typeof(int));
    
            var fotoParameter = foto != null ?
                new ObjectParameter("Foto", foto) :
                new ObjectParameter("Foto", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("USUARIO_C_REGISTRO", loginNameParameter, passwordParameter, nombreParameter, paternoParameter, maternoParameter, idPuestoParameter, usuarioParameter, idClinicaParameter, idEspecialidadParameter, fotoParameter);
        }
    
        public virtual ObjectResult<Usuario_R_DATOS_Result> Usuario_R_DATOS(string usuario, string ip)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var ipParameter = ip != null ?
                new ObjectParameter("Ip", ip) :
                new ObjectParameter("Ip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usuario_R_DATOS_Result>("Usuario_R_DATOS", usuarioParameter, ipParameter);
        }
    
        public virtual ObjectResult<Usuario_R_Login_Result> Usuario_R_Login(string loginName, string contraseña, string usuario, string ip)
        {
            var loginNameParameter = loginName != null ?
                new ObjectParameter("LoginName", loginName) :
                new ObjectParameter("LoginName", typeof(string));
    
            var contraseñaParameter = contraseña != null ?
                new ObjectParameter("Contraseña", contraseña) :
                new ObjectParameter("Contraseña", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var ipParameter = ip != null ?
                new ObjectParameter("Ip", ip) :
                new ObjectParameter("Ip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usuario_R_Login_Result>("Usuario_R_Login", loginNameParameter, contraseñaParameter, usuarioParameter, ipParameter);
        }
    
        public virtual int Usuario_U_PreferenciaColor(Nullable<int> idUsuario, Nullable<int> idPreferencia)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var idPreferenciaParameter = idPreferencia.HasValue ?
                new ObjectParameter("IdPreferencia", idPreferencia) :
                new ObjectParameter("IdPreferencia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Usuario_U_PreferenciaColor", idUsuarioParameter, idPreferenciaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Usuario_U_REGISTRO(Nullable<int> idUsuario, string loginName, string password, string nombre, string paterno, string materno, Nullable<int> idPuesto, string usuario, byte[] foto)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var loginNameParameter = loginName != null ?
                new ObjectParameter("LoginName", loginName) :
                new ObjectParameter("LoginName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var paternoParameter = paterno != null ?
                new ObjectParameter("Paterno", paterno) :
                new ObjectParameter("Paterno", typeof(string));
    
            var maternoParameter = materno != null ?
                new ObjectParameter("Materno", materno) :
                new ObjectParameter("Materno", typeof(string));
    
            var idPuestoParameter = idPuesto.HasValue ?
                new ObjectParameter("IdPuesto", idPuesto) :
                new ObjectParameter("IdPuesto", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var fotoParameter = foto != null ?
                new ObjectParameter("Foto", foto) :
                new ObjectParameter("Foto", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Usuario_U_REGISTRO", idUsuarioParameter, loginNameParameter, passwordParameter, nombreParameter, paternoParameter, maternoParameter, idPuestoParameter, usuarioParameter, fotoParameter);
        }
    }
}
