//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manag.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rel_Especialidad_Imagen
    {
        public long IdRelacion { get; set; }
        public Nullable<int> IdEspecialidad { get; set; }
        public Nullable<int> Consecutivo { get; set; }
        public string Nombre { get; set; }
        public byte[] Imagen { get; set; }
    }
}
