//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manag.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rel_Consulta_Diagnostico
    {
        public long IdDiagnostico { get; set; }
        public long IdConsulta { get; set; }
        public string DescripcionDiagnostico { get; set; }
        public string Observacion { get; set; }
        public Nullable<bool> PrimeraVez { get; set; }
        public string Tipo { get; set; }
        public string CIE10 { get; set; }
    }
}
