//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manag.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int IdUsuario { get; set; }
        public Nullable<int> IdClinica { get; set; }
        public Nullable<int> IdEspecialidad { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string Nombre { get; set; }
        public string Paterno { get; set; }
        public string Materno { get; set; }
        public Nullable<int> IdPuesto { get; set; }
        public byte[] Foto { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public Nullable<bool> Inactivo { get; set; }
        public string Usuario1 { get; set; }
        public Nullable<int> PreferenciaColor { get; set; }
    }
}
